import { IconLink } from '@tabler/icons-react'
import { type ReactNode } from 'react'
import type { MDXComponents } from 'mdx/types.js'

/**
 * Split origignal document title and the anchor generated by gen-doc cli.
 *
 * @param mixedTitle original title, title and anchor are mixed in it.
 * @returns title and anchor strings.
 */
function splitTitleAndAnchor(mixedTitle: ReactNode): {
  title: ReactNode
  anchor: string
} {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const titleArray = Array.isArray(mixedTitle) ? [...mixedTitle] : [mixedTitle]
  const anchor = titleArray.at(-1) as string
  const title = titleArray.slice(0, -1) as ReactNode

  return {
    title,
    anchor: `title-${anchor}`,
  }
}

function _LinkIcon({ anchor }: { anchor: string }) {
  return (
    <a href={`#${anchor}`}>
      <IconLink size={18} />
    </a>
  )
}

/**
 * MDXComponents not works in wrapper like:
 *
 * ```jsx
 * export function Wrapper = () => (<MDXProvider components={mdxComponents}>{children}</MDXProvider>)
 *
 * <Wrapper>{children}</Wrapper>
 * ```
 *
 * where `children` is the document
 */
export const mdxComponents: MDXComponents = {
  h1: ({ children, ...props }) => {
    const { title, anchor } = splitTitleAndAnchor(children as ReactNode)
    return (
      <h1 {...props} id={anchor}>
        <_LinkIcon anchor={anchor} />
        {title}
      </h1>
    )
  },
  h2: ({ children, ...props }) => {
    const { title, anchor } = splitTitleAndAnchor(children as ReactNode)
    return (
      <h2 {...props} id={anchor}>
        <_LinkIcon anchor={anchor} />
        {title}
      </h2>
    )
  },
  h3: ({ children, ...props }) => {
    const { title, anchor } = splitTitleAndAnchor(children as ReactNode)
    return (
      <h3 {...props} id={anchor}>
        <_LinkIcon anchor={anchor} />
        {title}
      </h3>
    )
  },
  h4: ({ children, ...props }) => {
    const { title, anchor } = splitTitleAndAnchor(children as ReactNode)
    return (
      <h4 {...props} id={anchor}>
        <_LinkIcon anchor={anchor} />
        {title}
      </h4>
    )
  },
  h5: ({ children, ...props }) => {
    const { title, anchor } = splitTitleAndAnchor(children as ReactNode)
    return (
      <h5 {...props} id={anchor}>
        <_LinkIcon anchor={anchor} />
        {title}
      </h5>
    )
  },
  h6: ({ children, ...props }) => {
    const { title, anchor } = splitTitleAndAnchor(children as ReactNode)
    return (
      <h6 {...props} id={anchor}>
        <_LinkIcon anchor={anchor} />
        {title}
      </h6>
    )
  },
}
