import { IconLink } from '@tabler/icons-react'
import { useState, type HTMLAttributes, type ReactNode } from 'react'

/**
 * Split origignal document title and the anchor generated by gen-doc cli.
 *
 * @param mixedTitle original title, title and anchor are mixed in it.
 * @returns title and anchor strings.
 */
function splitTitleAndAnchor(mixedTitle: ReactNode): {
  title: ReactNode
  anchor: string
} {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const titleArray = Array.isArray(mixedTitle) ? [...mixedTitle] : [mixedTitle]
  const anchor = titleArray.at(-1) as string
  const title = titleArray.slice(0, -1) as ReactNode

  return {
    title,
    anchor: `title-${anchor}`,
  }
}

function _LinkIcon({
  anchor,
  className,
}: {
  anchor: string
  className?: string
}) {
  return (
    <a href={`#${anchor}`} className={className}>
      <IconLink size={18} />
    </a>
  )
}

interface _HeadingProps extends HTMLAttributes<HTMLHeadingElement> {
  level: 1 | 2 | 3 | 4 | 5 | 6
  children: ReactNode
  className?: string
  [key: string]: unknown
}

const HEADING_TAGS = {
  1: 'h1',
  2: 'h2',
  3: 'h3',
  4: 'h4',
  5: 'h5',
  6: 'h6',
} as const

export default function Heading({
  level,
  className,
  children,
  ...props
}: _HeadingProps) {
  const [showIcon, setShowIcon] = useState(false)

  const { title, anchor } = splitTitleAndAnchor(children)

  const commonClass = 'flex gap-2 my-article-paragraph items-center'
  const finalClassName = [commonClass, className].filter(Boolean).join(' ')
  const Tag = HEADING_TAGS[level]

  return (
    <>
      <Tag
        id={anchor}
        className={finalClassName}
        onMouseEnter={() => {
          setShowIcon(true)
        }}
        onMouseLeave={() => {
          setShowIcon(false)
        }}
        {...props}
      >
        {title}
        <_LinkIcon anchor={anchor} className={showIcon ? '' : 'hidden'} />
      </Tag>
    </>
  )
}
