import { IconCheck, IconLink } from '@tabler/icons-react'
import { useEffect, useState, type HTMLAttributes, type ReactNode } from 'react'
import { getI18n } from '@/i18n/i18n-context'
import { log } from '@/log'

/**
 * Split origignal document title and the anchor generated by gen-doc cli.
 *
 * @param mixedTitle original title, title and anchor are mixed in it.
 * @returns title and anchor strings.
 */
function splitTitleAndAnchor(mixedTitle: ReactNode): {
  title: ReactNode
  anchor: string
} {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const titleArray = Array.isArray(mixedTitle) ? [...mixedTitle] : [mixedTitle]
  const anchor = titleArray.at(-1) as string
  const title = titleArray.slice(0, -1) as ReactNode

  return {
    title,
    anchor: `title-${anchor}`,
  }
}

function _LinkIcon({
  anchor,
  className,
  showCopiedIcon,
}: {
  anchor: string
  className?: string
  showCopiedIcon: boolean
}) {
  const tr = getI18n().articlePage.components.heading.copyButton
  return (
    <a href={`#${anchor}`} className={className}>
      {showCopiedIcon ? (
        <IconCheck size={20} title={tr.copiedTooltip} />
      ) : (
        <IconLink size={20} title={tr.tooltip} className="hover:text-primary" />
      )}
    </a>
  )
}

interface _HeadingProps extends HTMLAttributes<HTMLHeadingElement> {
  level: 1 | 2 | 3 | 4 | 5 | 6
  children: ReactNode
  className?: string
  [key: string]: unknown
}

const HEADING_TAGS = {
  1: 'h1',
  2: 'h2',
  3: 'h3',
  4: 'h4',
  5: 'h5',
  6: 'h6',
} as const

export default function Heading({
  level,
  className,
  children,
  ...props
}: _HeadingProps) {
  const [showIcon, setShowIcon] = useState(false)
  const [justClicked, setJustClicked] = useState(false)

  const { title, anchor } = splitTitleAndAnchor(children)

  const commonClass =
    'flex gap-2 my-article-paragraph items-center font-bold py-2'
  const finalClassName = [commonClass, className].filter(Boolean).join(' ')
  const Tag = HEADING_TAGS[level]

  // After link button clicked, show check button for some duration and then
  // hide it.
  useEffect(() => {
    if (!justClicked) {
      return
    }

    const timer = setTimeout(() => {
      setShowIcon(false)
      setJustClicked(false)
    }, 2000)

    return () => {
      clearTimeout(timer)
    }
  }, [justClicked])

  return (
    <>
      <Tag
        id={anchor}
        className={finalClassName}
        onMouseEnter={() => {
          setShowIcon(true)
        }}
        onMouseLeave={() => {
          if (justClicked) {
            // The onClick handler delegates icon visibility.
            return
          }
          setShowIcon(false)
        }}
        {...props}
      >
        {title}
        <div
          onClick={() => {
            setJustClicked(true)
            const s = globalThis.location.toString()
            const idx = s.lastIndexOf('#')
            // Note that the url [s] here may have or not have anchor.
            // As we are using anchor urls here:
            // "domain/#/articles/article_title" does not have anchor to remove.
            // We should only remove anchors like "#foo" in "domain/#/articles/article_title#foo".
            //
            // Be careful to reserve the original '#' as hash url.
            const fullLink =
              (idx === s.indexOf('#') ? s : s.slice(0, idx)) + '#' + anchor
            navigator.clipboard.writeText(fullLink).catch((error: unknown) => {
              log('failed to copy heading url to clipboard', error)
            })
          }}
        >
          <_LinkIcon
            showCopiedIcon={justClicked}
            anchor={anchor}
            className={
              (showIcon ? '' : 'hidden') + (justClicked ? 'text-primary' : '')
            }
          />
        </div>
      </Tag>
    </>
  )
}
